# Project configuration
# =====================

name = "Kiwi"
#root = "http://localhost:3000"
root = "https://kiwilang.site"
license = "https://github.com/ButterSus/KiwiLang/blob/master/LICENSE"
version = "in Alpha"

# Urls
# ====

language-server-kiwi-url = "#"
vscode-kiwi-extension-url = "https://marketplace.visualstudio.com/items?itemName=ButterSus.kiwi-language"
kotlin_url = "https://kotlinlang.org"
kotlin_docs_url = "https://kotlinlang.org/docs/reference"
