[book]
title = "Kiwi Book"
description = "Documentation for the Kiwi programming language"
authors = ["ButterSus <eduardkrivosapkin5@gmail.com>"]
language = "en"
multilingual = false

[build]
build-dir = "../docs"

[output.html]
additional-js = [
    "./dist/index.js",  # syntax highlighting
]
additional-css = [
    "./mdbook-admonish.css",  # mkdocs-material
    "./index.css",   # custom css
    "./theme/catppuccin.css",  # new theme
    "./theme/catppuccin-highlight.css",  # new theme
]
default-theme = "light"
preferred-dark-theme = "macchiato"

[preprocessor]  # required
[preprocessor.tera]  # macros
[preprocessor.template]  # pug-like mixins
[preprocessor.admonish]  # mkdocs-material
command = "mdbook-admonish"
assets_version = "2.0.1"

[preprocessor.catppuccin]  # new theme
assets_version = "0.1.1"
