# BOOK INFO
# =========

[book]
title = "Kiwi Book"
description = "Documentation for the Kiwi programming language"
authors = ["ButterSus <eduardkrivosapkin5@gmail.com>"]
language = "en"
multilingual = false

# BUILD CONFIGURATION
# ===================

[build]
build-dir = "../docs"

# OUTPUT CONFIGURATION
# ====================

[output.html]
site-url = "https://kiwilang.site"
default-theme = "light"
preferred-dark-theme = "coal"
use-site-url-as-root = true
additional-js = [
    "./dist/highlight.js", # syntax highlighting
    "./dist/sidebar.js", # sidebar
    "./dist/pagetoc.js", # pagetoc
]
additional-css = [
    "./theme/mdbook-admonish.css", # mkdocs-material
    "./theme/index.css", # custom css
    "./theme/kiwi.css", # new theme
    "./theme/kiwi-highlight.css", # new theme
    "./theme/pagetoc.css", # pagetoc
]

# PLUGINS
# =======>

[preprocessor] # required by mdbook-admonish
[preprocessor.template] # adds custom templates
[preprocessor.admonish] # adds admonitions
command = "mdbook-admonish"
assets_version = "2.0.1"
[preprocessor.catppuccin] # adds new themes
assets_version = "0.1.1" # DO NOT EDIT: Managed by `mdbook-catppuccin install`
[preprocessor.variables] # adds macros
use_env = true # use environment variables

# ONLY MACROS ARE LOCATED BELOW
# =============================>
[preprocessor.variables.variables]



# Project variables
# ----------------->
name = "Kiwi"
license = "https://github.com/KiwiLang/KiwiLang/LICENSE"
version = "-.-.-"



# Social variables
# ---------------->
github-organization = "https://github.com/KiwiLang"
discord-invite = "https://discord.gg/hwznTdFHDj"



# Links variables
# --------------->
language-server-kiwi-url = "#"
vscode-extension-kiwi-url = "#"
kotlin-url = "https://kotlinlang.org"
kotlin-docs-url = "https://kotlinlang.org/docs/reference"
