# BOOK INFO
# =========

[book]
title = "Kiwi Book"
description = "Documentation for the Kiwi programming language"
authors = ["ButterSus <eduardkrivosapkin5@gmail.com>"]
language = "en"
multilingual = false
src = "src"

# BUILD CONFIGURATION
# ===================

[build]
build-dir = "../docs"

# OUTPUT CONFIGURATION
# ====================

[output.html]
site-url = "https://kiwilang.site"
default-theme = "light"
preferred-dark-theme = "coal"
use-site-url-as-root = true
additional-js = [
    "./dist/highlight.js", # syntax highlighting
    "./dist/sidebar.js", # sidebar
    "./dist/pagetoc.js", # pagetoc
]
additional-css = [
    "./theme/mdbook-admonish.css", # mkdocs-material
    "./theme/index.css", # custom css
    "./theme/kiwi.css", # new theme
    "./theme/kiwi-highlight.css", # new theme
    "./theme/pagetoc.css", # pagetoc
]

# PLUGINS
# =======>

[preprocessor] # required by mdbook-admonish
[preprocessor.emojicodes] # adds emojis
[preprocessor.template] # adds custom templates
[preprocessor.admonish] # adds admonitions
command = "mdbook-admonish"
assets_version = "2.0.1"
[preprocessor.catppuccin] # adds new themes
assets_version = "0.1.1" # DO NOT EDIT: Managed by `mdbook-catppuccin install`
[preprocessor.variables] # adds macros
use_env = true # use environment variables

# ONLY MACROS ARE LOCATED BELOW
# =============================>
[preprocessor.variables.variables]



# Project variables
# ----------------->
name = "Kiwi"
license = "https://github.com/KiwiLang/KiwiLang/LICENSE"
version = "-.-.-"



# Social variables
# ---------------->
github_repository = "https://github.com/KiwiLang/KiwiLang"
github_organization = "https://github.com/KiwiLang"
discord_invite = "https://discord.gg/hwznTdFHDj"
stackoverflow_tag = "https://stackoverflow.com/questions/tagged/kiwi-lang"



# Links variables
# --------------->
mdbook_url = "https://rust-lang.github.io/mdBook"
mdbook_template_url = "https://github.com/sgoudham/mdbook-template"
mdbook_admonish_url = "https://tommilligan.github.io/mdbook-admonish"
mdbook_catppuccino_url = "https://github.com/catppuccin/mdBook"
mdbook_variables_url = "https://crates.io/crates/mdbook-variables"
markdown_url = "https://www.markdownguide.org"

language_server-kiwi-url = "#"
vscode_extension-kiwi-url = "#"
kotlin_url = "https://kotlinlang.org"
kotlin_docs_url = "https://kotlinlang.org/docs/reference"
